// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital;

public final class ContinuousAssessment {
  private ContinuousAssessment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePatientProfileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePatientProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePatientProfileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePatientProfileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPatientMealsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPatientMealsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPatientMealsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPatientMealsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePatientMealsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePatientMealsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdatePatientMealsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdatePatientMealsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025patientsprofile.proto\"J\n\033CreatePatient" +
      "ProfileRequest\022\013\n\003age\030\001 \001(\005\022\016\n\006weight\030\002 " +
      "\001(\005\022\016\n\006height\030\003 \001(\005\"4\n\034CreatePatientProf" +
      "ileResponse\022\024\n\014confirmation\030\001 \001(\t\",\n\026Get" +
      "PatientMealsRequest\022\022\n\npatient_id\030\001 \001(\t\"" +
      "(\n\027GetPatientMealsResponse\022\r\n\005meals\030\001 \003(" +
      "\t\">\n\031UpdatePatientMealsRequest\022\022\n\npatien" +
      "t_id\030\001 \001(\t\022\r\n\005meals\030\002 \003(\t\"2\n\032UpdatePatie" +
      "ntMealsResponse\022\024\n\014confirmation\030\001 \001(\t2\207\002" +
      "\n\025PatientProfileService\022U\n\024CreatePatient" +
      "Profile\022\034.CreatePatientProfileRequest\032\035." +
      "CreatePatientProfileResponse\"\000\022F\n\017GetPat" +
      "ientMeals\022\027.GetPatientMealsRequest\032\030.Get" +
      "PatientMealsResponse\"\000\022O\n\022UpdatePatientM" +
      "eals\022\032.UpdatePatientMealsRequest\032\033.Updat" +
      "ePatientMealsResponse\"\000B&\n\014com.hospitalB" +
      "\024ContinuousAssessmentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CreatePatientProfileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreatePatientProfileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePatientProfileRequest_descriptor,
        new java.lang.String[] { "Age", "Weight", "Height", });
    internal_static_CreatePatientProfileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreatePatientProfileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePatientProfileResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_GetPatientMealsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetPatientMealsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPatientMealsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_GetPatientMealsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetPatientMealsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPatientMealsResponse_descriptor,
        new java.lang.String[] { "Meals", });
    internal_static_UpdatePatientMealsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UpdatePatientMealsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePatientMealsRequest_descriptor,
        new java.lang.String[] { "PatientId", "Meals", });
    internal_static_UpdatePatientMealsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UpdatePatientMealsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdatePatientMealsResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
