// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital;

public interface CreatePatientProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreatePatientProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>int32 weight = 2;</code>
   */
  int getWeight();

  /**
   * <code>int32 height = 3;</code>
   */
  int getHeight();
}
