// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portioncalculator.proto

package com.hospital;

public interface CurrentPortionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrentPortionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string meal = 2;</code>
   */
  java.lang.String getMeal();
  /**
   * <code>string meal = 2;</code>
   */
  com.google.protobuf.ByteString
      getMealBytes();
}
