// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portioncalculator.proto

package com.hospital;

public interface DailyMealsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DailyMealsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string meals = 1;</code>
   */
  java.util.List<java.lang.String>
      getMealsList();
  /**
   * <code>repeated string meals = 1;</code>
   */
  int getMealsCount();
  /**
   * <code>repeated string meals = 1;</code>
   */
  java.lang.String getMeals(int index);
  /**
   * <code>repeated string meals = 1;</code>
   */
  com.google.protobuf.ByteString
      getMealsBytes(int index);
}
