// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital;

public interface MealRankingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MealRankingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool confirmation = 1;</code>
   */
  boolean getConfirmation();
}
