// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital;

public interface MealRankingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MealRankingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 digit_number = 1;</code>
   */
  int getDigitNumber();
}
