// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital;

public interface MicroNutrientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MicroNutrientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float calories = 1;</code>
   */
  float getCalories();

  /**
   * <code>int32 diet_level = 2;</code>
   */
  int getDietLevel();
}
