// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital;

public interface MicroNutrientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MicroNutrientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meal_name = 1;</code>
   */
  java.lang.String getMealName();
  /**
   * <code>string meal_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getMealNameBytes();
}
