// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital;

public interface NutriInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NutriInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meal_name = 1;</code>
   */
  java.lang.String getMealName();
  /**
   * <code>string meal_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getMealNameBytes();

  /**
   * <code>float calories = 2;</code>
   */
  float getCalories();

  /**
   * <code>float protein = 3;</code>
   */
  float getProtein();

  /**
   * <code>float carbohydrates = 4;</code>
   */
  float getCarbohydrates();

  /**
   * <code>float fat = 5;</code>
   */
  float getFat();
}
