// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital;

public interface UpdatePatientMealsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdatePatientMealsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_id = 1;</code>
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>repeated string meals = 2;</code>
   */
  java.util.List<java.lang.String>
      getMealsList();
  /**
   * <code>repeated string meals = 2;</code>
   */
  int getMealsCount();
  /**
   * <code>repeated string meals = 2;</code>
   */
  java.lang.String getMeals(int index);
  /**
   * <code>repeated string meals = 2;</code>
   */
  com.google.protobuf.ByteString
      getMealsBytes(int index);
}
