// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital.patientsprofile;

public final class ContinuousAssessment {
  private ContinuousAssessment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPatientInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPatientInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPatientInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPatientInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDailyMealsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDailyMealsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDailyMealsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDailyMealsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDailyMealsResponse_Meal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDailyMealsResponse_Meal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLunchDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetLunchDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLunchDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetLunchDetailsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLunchDetailsResponse_Meal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetLunchDetailsResponse_Meal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025patientsprofile.proto\"+\n\025GetPatientInf" +
      "oRequest\022\022\n\npatient_id\030\001 \001(\t\"N\n\026GetPatie" +
      "ntInfoResponse\022\024\n\014patient_name\030\001 \001(\t\022\016\n\006" +
      "height\030\002 \001(\002\022\016\n\006weight\030\003 \001(\002\"*\n\024GetDaily" +
      "MealsRequest\022\022\n\npatient_id\030\001 \001(\t\"\327\001\n\025Get" +
      "DailyMealsResponse\022.\n\tbreakfast\030\001 \003(\0132\033." +
      "GetDailyMealsResponse.Meal\022*\n\005lunch\030\002 \003(" +
      "\0132\033.GetDailyMealsResponse.Meal\022+\n\006dinner" +
      "\030\003 \003(\0132\033.GetDailyMealsResponse.Meal\0325\n\004M" +
      "eal\022\014\n\004food\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\002\022\r\n\005n" +
      "otes\030\003 \001(\t\",\n\026GetLunchDetailsRequest\022\022\n\n" +
      "patient_id\030\001 \001(\t\"~\n\027GetLunchDetailsRespo" +
      "nse\022,\n\005meals\030\001 \003(\0132\035.GetLunchDetailsResp" +
      "onse.Meal\0325\n\004Meal\022\014\n\004food\030\001 \001(\t\022\020\n\010quant" +
      "ity\030\002 \001(\002\022\r\n\005notes\030\003 \001(\t2\350\001\n\025PatientProf" +
      "ileService\022C\n\016GetPatientInfo\022\026.GetPatien" +
      "tInfoRequest\032\027.GetPatientInfoResponse\"\000\022" +
      "B\n\rGetDailyMeals\022\025.GetDailyMealsRequest\032" +
      "\026.GetDailyMealsResponse\"\0000\001\022F\n\017GetLunchD" +
      "etails\022\027.GetLunchDetailsRequest\032\030.GetLun" +
      "chDetailsResponse\"\000B6\n\034com.hospital.pati" +
      "entsprofileB\024ContinuousAssessmentP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetPatientInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetPatientInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPatientInfoRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_GetPatientInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetPatientInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPatientInfoResponse_descriptor,
        new java.lang.String[] { "PatientName", "Height", "Weight", });
    internal_static_GetDailyMealsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetDailyMealsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDailyMealsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_GetDailyMealsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetDailyMealsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDailyMealsResponse_descriptor,
        new java.lang.String[] { "Breakfast", "Lunch", "Dinner", });
    internal_static_GetDailyMealsResponse_Meal_descriptor =
      internal_static_GetDailyMealsResponse_descriptor.getNestedTypes().get(0);
    internal_static_GetDailyMealsResponse_Meal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDailyMealsResponse_Meal_descriptor,
        new java.lang.String[] { "Food", "Quantity", "Notes", });
    internal_static_GetLunchDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetLunchDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetLunchDetailsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_GetLunchDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetLunchDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetLunchDetailsResponse_descriptor,
        new java.lang.String[] { "Meals", });
    internal_static_GetLunchDetailsResponse_Meal_descriptor =
      internal_static_GetLunchDetailsResponse_descriptor.getNestedTypes().get(0);
    internal_static_GetLunchDetailsResponse_Meal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetLunchDetailsResponse_Meal_descriptor,
        new java.lang.String[] { "Food", "Quantity", "Notes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
