// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital.patientsprofile;

public interface GetDailyMealsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDailyMealsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> 
      getBreakfastList();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  com.hospital.patientsprofile.GetDailyMealsResponse.Meal getBreakfast(int index);
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  int getBreakfastCount();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
      getBreakfastOrBuilderList();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getBreakfastOrBuilder(
      int index);

  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> 
      getLunchList();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  com.hospital.patientsprofile.GetDailyMealsResponse.Meal getLunch(int index);
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  int getLunchCount();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
      getLunchOrBuilderList();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getLunchOrBuilder(
      int index);

  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> 
      getDinnerList();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  com.hospital.patientsprofile.GetDailyMealsResponse.Meal getDinner(int index);
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  int getDinnerCount();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
      getDinnerOrBuilderList();
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getDinnerOrBuilder(
      int index);
}
