// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital.patientsprofile;

/**
 * Protobuf type {@code GetDailyMealsResponse}
 */
public  final class GetDailyMealsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetDailyMealsResponse)
    GetDailyMealsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetDailyMealsResponse.newBuilder() to construct.
  private GetDailyMealsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetDailyMealsResponse() {
    breakfast_ = java.util.Collections.emptyList();
    lunch_ = java.util.Collections.emptyList();
    dinner_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetDailyMealsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              breakfast_ = new java.util.ArrayList<com.hospital.patientsprofile.GetDailyMealsResponse.Meal>();
              mutable_bitField0_ |= 0x00000001;
            }
            breakfast_.add(
                input.readMessage(com.hospital.patientsprofile.GetDailyMealsResponse.Meal.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              lunch_ = new java.util.ArrayList<com.hospital.patientsprofile.GetDailyMealsResponse.Meal>();
              mutable_bitField0_ |= 0x00000002;
            }
            lunch_.add(
                input.readMessage(com.hospital.patientsprofile.GetDailyMealsResponse.Meal.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              dinner_ = new java.util.ArrayList<com.hospital.patientsprofile.GetDailyMealsResponse.Meal>();
              mutable_bitField0_ |= 0x00000004;
            }
            dinner_.add(
                input.readMessage(com.hospital.patientsprofile.GetDailyMealsResponse.Meal.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        breakfast_ = java.util.Collections.unmodifiableList(breakfast_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        lunch_ = java.util.Collections.unmodifiableList(lunch_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        dinner_ = java.util.Collections.unmodifiableList(dinner_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hospital.patientsprofile.GetDailyMealsResponse.class, com.hospital.patientsprofile.GetDailyMealsResponse.Builder.class);
  }

  public interface MealOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetDailyMealsResponse.Meal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string food = 1;</code>
     */
    java.lang.String getFood();
    /**
     * <code>string food = 1;</code>
     */
    com.google.protobuf.ByteString
        getFoodBytes();

    /**
     * <code>float quantity = 2;</code>
     */
    float getQuantity();

    /**
     * <code>string notes = 3;</code>
     */
    java.lang.String getNotes();
    /**
     * <code>string notes = 3;</code>
     */
    com.google.protobuf.ByteString
        getNotesBytes();
  }
  /**
   * Protobuf type {@code GetDailyMealsResponse.Meal}
   */
  public  static final class Meal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetDailyMealsResponse.Meal)
      MealOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Meal.newBuilder() to construct.
    private Meal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meal() {
      food_ = "";
      quantity_ = 0F;
      notes_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Meal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              food_ = s;
              break;
            }
            case 21: {

              quantity_ = input.readFloat();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              notes_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_Meal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_Meal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hospital.patientsprofile.GetDailyMealsResponse.Meal.class, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder.class);
    }

    public static final int FOOD_FIELD_NUMBER = 1;
    private volatile java.lang.Object food_;
    /**
     * <code>string food = 1;</code>
     */
    public java.lang.String getFood() {
      java.lang.Object ref = food_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        food_ = s;
        return s;
      }
    }
    /**
     * <code>string food = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFoodBytes() {
      java.lang.Object ref = food_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        food_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private float quantity_;
    /**
     * <code>float quantity = 2;</code>
     */
    public float getQuantity() {
      return quantity_;
    }

    public static final int NOTES_FIELD_NUMBER = 3;
    private volatile java.lang.Object notes_;
    /**
     * <code>string notes = 3;</code>
     */
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      }
    }
    /**
     * <code>string notes = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFoodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, food_);
      }
      if (quantity_ != 0F) {
        output.writeFloat(2, quantity_);
      }
      if (!getNotesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, notes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFoodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, food_);
      }
      if (quantity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, quantity_);
      }
      if (!getNotesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, notes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hospital.patientsprofile.GetDailyMealsResponse.Meal)) {
        return super.equals(obj);
      }
      com.hospital.patientsprofile.GetDailyMealsResponse.Meal other = (com.hospital.patientsprofile.GetDailyMealsResponse.Meal) obj;

      boolean result = true;
      result = result && getFood()
          .equals(other.getFood());
      result = result && (
          java.lang.Float.floatToIntBits(getQuantity())
          == java.lang.Float.floatToIntBits(
              other.getQuantity()));
      result = result && getNotes()
          .equals(other.getNotes());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FOOD_FIELD_NUMBER;
      hash = (53 * hash) + getFood().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getQuantity());
      hash = (37 * hash) + NOTES_FIELD_NUMBER;
      hash = (53 * hash) + getNotes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hospital.patientsprofile.GetDailyMealsResponse.Meal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetDailyMealsResponse.Meal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetDailyMealsResponse.Meal)
        com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_Meal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_Meal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hospital.patientsprofile.GetDailyMealsResponse.Meal.class, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder.class);
      }

      // Construct using com.hospital.patientsprofile.GetDailyMealsResponse.Meal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        food_ = "";

        quantity_ = 0F;

        notes_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_Meal_descriptor;
      }

      @java.lang.Override
      public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getDefaultInstanceForType() {
        return com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance();
      }

      @java.lang.Override
      public com.hospital.patientsprofile.GetDailyMealsResponse.Meal build() {
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hospital.patientsprofile.GetDailyMealsResponse.Meal buildPartial() {
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal result = new com.hospital.patientsprofile.GetDailyMealsResponse.Meal(this);
        result.food_ = food_;
        result.quantity_ = quantity_;
        result.notes_ = notes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hospital.patientsprofile.GetDailyMealsResponse.Meal) {
          return mergeFrom((com.hospital.patientsprofile.GetDailyMealsResponse.Meal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hospital.patientsprofile.GetDailyMealsResponse.Meal other) {
        if (other == com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance()) return this;
        if (!other.getFood().isEmpty()) {
          food_ = other.food_;
          onChanged();
        }
        if (other.getQuantity() != 0F) {
          setQuantity(other.getQuantity());
        }
        if (!other.getNotes().isEmpty()) {
          notes_ = other.notes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hospital.patientsprofile.GetDailyMealsResponse.Meal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object food_ = "";
      /**
       * <code>string food = 1;</code>
       */
      public java.lang.String getFood() {
        java.lang.Object ref = food_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          food_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string food = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFoodBytes() {
        java.lang.Object ref = food_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          food_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string food = 1;</code>
       */
      public Builder setFood(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        food_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string food = 1;</code>
       */
      public Builder clearFood() {
        
        food_ = getDefaultInstance().getFood();
        onChanged();
        return this;
      }
      /**
       * <code>string food = 1;</code>
       */
      public Builder setFoodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        food_ = value;
        onChanged();
        return this;
      }

      private float quantity_ ;
      /**
       * <code>float quantity = 2;</code>
       */
      public float getQuantity() {
        return quantity_;
      }
      /**
       * <code>float quantity = 2;</code>
       */
      public Builder setQuantity(float value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float quantity = 2;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object notes_ = "";
      /**
       * <code>string notes = 3;</code>
       */
      public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string notes = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string notes = 3;</code>
       */
      public Builder setNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        notes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string notes = 3;</code>
       */
      public Builder clearNotes() {
        
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      /**
       * <code>string notes = 3;</code>
       */
      public Builder setNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        notes_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetDailyMealsResponse.Meal)
    }

    // @@protoc_insertion_point(class_scope:GetDailyMealsResponse.Meal)
    private static final com.hospital.patientsprofile.GetDailyMealsResponse.Meal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hospital.patientsprofile.GetDailyMealsResponse.Meal();
    }

    public static com.hospital.patientsprofile.GetDailyMealsResponse.Meal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Meal>
        PARSER = new com.google.protobuf.AbstractParser<Meal>() {
      @java.lang.Override
      public Meal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Meal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Meal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int BREAKFAST_FIELD_NUMBER = 1;
  private java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> breakfast_;
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> getBreakfastList() {
    return breakfast_;
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  public java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
      getBreakfastOrBuilderList() {
    return breakfast_;
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  public int getBreakfastCount() {
    return breakfast_.size();
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getBreakfast(int index) {
    return breakfast_.get(index);
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
   */
  public com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getBreakfastOrBuilder(
      int index) {
    return breakfast_.get(index);
  }

  public static final int LUNCH_FIELD_NUMBER = 2;
  private java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> lunch_;
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> getLunchList() {
    return lunch_;
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  public java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
      getLunchOrBuilderList() {
    return lunch_;
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  public int getLunchCount() {
    return lunch_.size();
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getLunch(int index) {
    return lunch_.get(index);
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
   */
  public com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getLunchOrBuilder(
      int index) {
    return lunch_.get(index);
  }

  public static final int DINNER_FIELD_NUMBER = 3;
  private java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> dinner_;
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> getDinnerList() {
    return dinner_;
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  public java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
      getDinnerOrBuilderList() {
    return dinner_;
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  public int getDinnerCount() {
    return dinner_.size();
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getDinner(int index) {
    return dinner_.get(index);
  }
  /**
   * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
   */
  public com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getDinnerOrBuilder(
      int index) {
    return dinner_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < breakfast_.size(); i++) {
      output.writeMessage(1, breakfast_.get(i));
    }
    for (int i = 0; i < lunch_.size(); i++) {
      output.writeMessage(2, lunch_.get(i));
    }
    for (int i = 0; i < dinner_.size(); i++) {
      output.writeMessage(3, dinner_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < breakfast_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, breakfast_.get(i));
    }
    for (int i = 0; i < lunch_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, lunch_.get(i));
    }
    for (int i = 0; i < dinner_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, dinner_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hospital.patientsprofile.GetDailyMealsResponse)) {
      return super.equals(obj);
    }
    com.hospital.patientsprofile.GetDailyMealsResponse other = (com.hospital.patientsprofile.GetDailyMealsResponse) obj;

    boolean result = true;
    result = result && getBreakfastList()
        .equals(other.getBreakfastList());
    result = result && getLunchList()
        .equals(other.getLunchList());
    result = result && getDinnerList()
        .equals(other.getDinnerList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBreakfastCount() > 0) {
      hash = (37 * hash) + BREAKFAST_FIELD_NUMBER;
      hash = (53 * hash) + getBreakfastList().hashCode();
    }
    if (getLunchCount() > 0) {
      hash = (37 * hash) + LUNCH_FIELD_NUMBER;
      hash = (53 * hash) + getLunchList().hashCode();
    }
    if (getDinnerCount() > 0) {
      hash = (37 * hash) + DINNER_FIELD_NUMBER;
      hash = (53 * hash) + getDinnerList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.patientsprofile.GetDailyMealsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hospital.patientsprofile.GetDailyMealsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetDailyMealsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetDailyMealsResponse)
      com.hospital.patientsprofile.GetDailyMealsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hospital.patientsprofile.GetDailyMealsResponse.class, com.hospital.patientsprofile.GetDailyMealsResponse.Builder.class);
    }

    // Construct using com.hospital.patientsprofile.GetDailyMealsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBreakfastFieldBuilder();
        getLunchFieldBuilder();
        getDinnerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (breakfastBuilder_ == null) {
        breakfast_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        breakfastBuilder_.clear();
      }
      if (lunchBuilder_ == null) {
        lunch_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        lunchBuilder_.clear();
      }
      if (dinnerBuilder_ == null) {
        dinner_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        dinnerBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetDailyMealsResponse_descriptor;
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetDailyMealsResponse getDefaultInstanceForType() {
      return com.hospital.patientsprofile.GetDailyMealsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetDailyMealsResponse build() {
      com.hospital.patientsprofile.GetDailyMealsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetDailyMealsResponse buildPartial() {
      com.hospital.patientsprofile.GetDailyMealsResponse result = new com.hospital.patientsprofile.GetDailyMealsResponse(this);
      int from_bitField0_ = bitField0_;
      if (breakfastBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          breakfast_ = java.util.Collections.unmodifiableList(breakfast_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.breakfast_ = breakfast_;
      } else {
        result.breakfast_ = breakfastBuilder_.build();
      }
      if (lunchBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          lunch_ = java.util.Collections.unmodifiableList(lunch_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.lunch_ = lunch_;
      } else {
        result.lunch_ = lunchBuilder_.build();
      }
      if (dinnerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          dinner_ = java.util.Collections.unmodifiableList(dinner_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.dinner_ = dinner_;
      } else {
        result.dinner_ = dinnerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hospital.patientsprofile.GetDailyMealsResponse) {
        return mergeFrom((com.hospital.patientsprofile.GetDailyMealsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hospital.patientsprofile.GetDailyMealsResponse other) {
      if (other == com.hospital.patientsprofile.GetDailyMealsResponse.getDefaultInstance()) return this;
      if (breakfastBuilder_ == null) {
        if (!other.breakfast_.isEmpty()) {
          if (breakfast_.isEmpty()) {
            breakfast_ = other.breakfast_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBreakfastIsMutable();
            breakfast_.addAll(other.breakfast_);
          }
          onChanged();
        }
      } else {
        if (!other.breakfast_.isEmpty()) {
          if (breakfastBuilder_.isEmpty()) {
            breakfastBuilder_.dispose();
            breakfastBuilder_ = null;
            breakfast_ = other.breakfast_;
            bitField0_ = (bitField0_ & ~0x00000001);
            breakfastBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBreakfastFieldBuilder() : null;
          } else {
            breakfastBuilder_.addAllMessages(other.breakfast_);
          }
        }
      }
      if (lunchBuilder_ == null) {
        if (!other.lunch_.isEmpty()) {
          if (lunch_.isEmpty()) {
            lunch_ = other.lunch_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLunchIsMutable();
            lunch_.addAll(other.lunch_);
          }
          onChanged();
        }
      } else {
        if (!other.lunch_.isEmpty()) {
          if (lunchBuilder_.isEmpty()) {
            lunchBuilder_.dispose();
            lunchBuilder_ = null;
            lunch_ = other.lunch_;
            bitField0_ = (bitField0_ & ~0x00000002);
            lunchBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLunchFieldBuilder() : null;
          } else {
            lunchBuilder_.addAllMessages(other.lunch_);
          }
        }
      }
      if (dinnerBuilder_ == null) {
        if (!other.dinner_.isEmpty()) {
          if (dinner_.isEmpty()) {
            dinner_ = other.dinner_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDinnerIsMutable();
            dinner_.addAll(other.dinner_);
          }
          onChanged();
        }
      } else {
        if (!other.dinner_.isEmpty()) {
          if (dinnerBuilder_.isEmpty()) {
            dinnerBuilder_.dispose();
            dinnerBuilder_ = null;
            dinner_ = other.dinner_;
            bitField0_ = (bitField0_ & ~0x00000004);
            dinnerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDinnerFieldBuilder() : null;
          } else {
            dinnerBuilder_.addAllMessages(other.dinner_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hospital.patientsprofile.GetDailyMealsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hospital.patientsprofile.GetDailyMealsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> breakfast_ =
      java.util.Collections.emptyList();
    private void ensureBreakfastIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        breakfast_ = new java.util.ArrayList<com.hospital.patientsprofile.GetDailyMealsResponse.Meal>(breakfast_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> breakfastBuilder_;

    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> getBreakfastList() {
      if (breakfastBuilder_ == null) {
        return java.util.Collections.unmodifiableList(breakfast_);
      } else {
        return breakfastBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public int getBreakfastCount() {
      if (breakfastBuilder_ == null) {
        return breakfast_.size();
      } else {
        return breakfastBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getBreakfast(int index) {
      if (breakfastBuilder_ == null) {
        return breakfast_.get(index);
      } else {
        return breakfastBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder setBreakfast(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (breakfastBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBreakfastIsMutable();
        breakfast_.set(index, value);
        onChanged();
      } else {
        breakfastBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder setBreakfast(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (breakfastBuilder_ == null) {
        ensureBreakfastIsMutable();
        breakfast_.set(index, builderForValue.build());
        onChanged();
      } else {
        breakfastBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder addBreakfast(com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (breakfastBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBreakfastIsMutable();
        breakfast_.add(value);
        onChanged();
      } else {
        breakfastBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder addBreakfast(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (breakfastBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBreakfastIsMutable();
        breakfast_.add(index, value);
        onChanged();
      } else {
        breakfastBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder addBreakfast(
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (breakfastBuilder_ == null) {
        ensureBreakfastIsMutable();
        breakfast_.add(builderForValue.build());
        onChanged();
      } else {
        breakfastBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder addBreakfast(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (breakfastBuilder_ == null) {
        ensureBreakfastIsMutable();
        breakfast_.add(index, builderForValue.build());
        onChanged();
      } else {
        breakfastBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder addAllBreakfast(
        java.lang.Iterable<? extends com.hospital.patientsprofile.GetDailyMealsResponse.Meal> values) {
      if (breakfastBuilder_ == null) {
        ensureBreakfastIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, breakfast_);
        onChanged();
      } else {
        breakfastBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder clearBreakfast() {
      if (breakfastBuilder_ == null) {
        breakfast_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        breakfastBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public Builder removeBreakfast(int index) {
      if (breakfastBuilder_ == null) {
        ensureBreakfastIsMutable();
        breakfast_.remove(index);
        onChanged();
      } else {
        breakfastBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder getBreakfastBuilder(
        int index) {
      return getBreakfastFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getBreakfastOrBuilder(
        int index) {
      if (breakfastBuilder_ == null) {
        return breakfast_.get(index);  } else {
        return breakfastBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
         getBreakfastOrBuilderList() {
      if (breakfastBuilder_ != null) {
        return breakfastBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(breakfast_);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder addBreakfastBuilder() {
      return getBreakfastFieldBuilder().addBuilder(
          com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder addBreakfastBuilder(
        int index) {
      return getBreakfastFieldBuilder().addBuilder(
          index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal breakfast = 1;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder> 
         getBreakfastBuilderList() {
      return getBreakfastFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
        getBreakfastFieldBuilder() {
      if (breakfastBuilder_ == null) {
        breakfastBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder>(
                breakfast_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        breakfast_ = null;
      }
      return breakfastBuilder_;
    }

    private java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> lunch_ =
      java.util.Collections.emptyList();
    private void ensureLunchIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        lunch_ = new java.util.ArrayList<com.hospital.patientsprofile.GetDailyMealsResponse.Meal>(lunch_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> lunchBuilder_;

    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> getLunchList() {
      if (lunchBuilder_ == null) {
        return java.util.Collections.unmodifiableList(lunch_);
      } else {
        return lunchBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public int getLunchCount() {
      if (lunchBuilder_ == null) {
        return lunch_.size();
      } else {
        return lunchBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getLunch(int index) {
      if (lunchBuilder_ == null) {
        return lunch_.get(index);
      } else {
        return lunchBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder setLunch(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (lunchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLunchIsMutable();
        lunch_.set(index, value);
        onChanged();
      } else {
        lunchBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder setLunch(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (lunchBuilder_ == null) {
        ensureLunchIsMutable();
        lunch_.set(index, builderForValue.build());
        onChanged();
      } else {
        lunchBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder addLunch(com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (lunchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLunchIsMutable();
        lunch_.add(value);
        onChanged();
      } else {
        lunchBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder addLunch(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (lunchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLunchIsMutable();
        lunch_.add(index, value);
        onChanged();
      } else {
        lunchBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder addLunch(
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (lunchBuilder_ == null) {
        ensureLunchIsMutable();
        lunch_.add(builderForValue.build());
        onChanged();
      } else {
        lunchBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder addLunch(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (lunchBuilder_ == null) {
        ensureLunchIsMutable();
        lunch_.add(index, builderForValue.build());
        onChanged();
      } else {
        lunchBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder addAllLunch(
        java.lang.Iterable<? extends com.hospital.patientsprofile.GetDailyMealsResponse.Meal> values) {
      if (lunchBuilder_ == null) {
        ensureLunchIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lunch_);
        onChanged();
      } else {
        lunchBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder clearLunch() {
      if (lunchBuilder_ == null) {
        lunch_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        lunchBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public Builder removeLunch(int index) {
      if (lunchBuilder_ == null) {
        ensureLunchIsMutable();
        lunch_.remove(index);
        onChanged();
      } else {
        lunchBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder getLunchBuilder(
        int index) {
      return getLunchFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getLunchOrBuilder(
        int index) {
      if (lunchBuilder_ == null) {
        return lunch_.get(index);  } else {
        return lunchBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
         getLunchOrBuilderList() {
      if (lunchBuilder_ != null) {
        return lunchBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(lunch_);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder addLunchBuilder() {
      return getLunchFieldBuilder().addBuilder(
          com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder addLunchBuilder(
        int index) {
      return getLunchFieldBuilder().addBuilder(
          index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal lunch = 2;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder> 
         getLunchBuilderList() {
      return getLunchFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
        getLunchFieldBuilder() {
      if (lunchBuilder_ == null) {
        lunchBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder>(
                lunch_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        lunch_ = null;
      }
      return lunchBuilder_;
    }

    private java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> dinner_ =
      java.util.Collections.emptyList();
    private void ensureDinnerIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        dinner_ = new java.util.ArrayList<com.hospital.patientsprofile.GetDailyMealsResponse.Meal>(dinner_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> dinnerBuilder_;

    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal> getDinnerList() {
      if (dinnerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dinner_);
      } else {
        return dinnerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public int getDinnerCount() {
      if (dinnerBuilder_ == null) {
        return dinner_.size();
      } else {
        return dinnerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal getDinner(int index) {
      if (dinnerBuilder_ == null) {
        return dinner_.get(index);
      } else {
        return dinnerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder setDinner(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (dinnerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDinnerIsMutable();
        dinner_.set(index, value);
        onChanged();
      } else {
        dinnerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder setDinner(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (dinnerBuilder_ == null) {
        ensureDinnerIsMutable();
        dinner_.set(index, builderForValue.build());
        onChanged();
      } else {
        dinnerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder addDinner(com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (dinnerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDinnerIsMutable();
        dinner_.add(value);
        onChanged();
      } else {
        dinnerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder addDinner(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal value) {
      if (dinnerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDinnerIsMutable();
        dinner_.add(index, value);
        onChanged();
      } else {
        dinnerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder addDinner(
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (dinnerBuilder_ == null) {
        ensureDinnerIsMutable();
        dinner_.add(builderForValue.build());
        onChanged();
      } else {
        dinnerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder addDinner(
        int index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder builderForValue) {
      if (dinnerBuilder_ == null) {
        ensureDinnerIsMutable();
        dinner_.add(index, builderForValue.build());
        onChanged();
      } else {
        dinnerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder addAllDinner(
        java.lang.Iterable<? extends com.hospital.patientsprofile.GetDailyMealsResponse.Meal> values) {
      if (dinnerBuilder_ == null) {
        ensureDinnerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dinner_);
        onChanged();
      } else {
        dinnerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder clearDinner() {
      if (dinnerBuilder_ == null) {
        dinner_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        dinnerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public Builder removeDinner(int index) {
      if (dinnerBuilder_ == null) {
        ensureDinnerIsMutable();
        dinner_.remove(index);
        onChanged();
      } else {
        dinnerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder getDinnerBuilder(
        int index) {
      return getDinnerFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder getDinnerOrBuilder(
        int index) {
      if (dinnerBuilder_ == null) {
        return dinner_.get(index);  } else {
        return dinnerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public java.util.List<? extends com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
         getDinnerOrBuilderList() {
      if (dinnerBuilder_ != null) {
        return dinnerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dinner_);
      }
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder addDinnerBuilder() {
      return getDinnerFieldBuilder().addBuilder(
          com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder addDinnerBuilder(
        int index) {
      return getDinnerFieldBuilder().addBuilder(
          index, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetDailyMealsResponse.Meal dinner = 3;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder> 
         getDinnerBuilderList() {
      return getDinnerFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder> 
        getDinnerFieldBuilder() {
      if (dinnerBuilder_ == null) {
        dinnerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hospital.patientsprofile.GetDailyMealsResponse.Meal, com.hospital.patientsprofile.GetDailyMealsResponse.Meal.Builder, com.hospital.patientsprofile.GetDailyMealsResponse.MealOrBuilder>(
                dinner_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        dinner_ = null;
      }
      return dinnerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetDailyMealsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetDailyMealsResponse)
  private static final com.hospital.patientsprofile.GetDailyMealsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hospital.patientsprofile.GetDailyMealsResponse();
  }

  public static com.hospital.patientsprofile.GetDailyMealsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDailyMealsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetDailyMealsResponse>() {
    @java.lang.Override
    public GetDailyMealsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetDailyMealsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetDailyMealsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetDailyMealsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hospital.patientsprofile.GetDailyMealsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

