// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital.patientsprofile;

/**
 * Protobuf type {@code GetLunchDetailsResponse}
 */
public  final class GetLunchDetailsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetLunchDetailsResponse)
    GetLunchDetailsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLunchDetailsResponse.newBuilder() to construct.
  private GetLunchDetailsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLunchDetailsResponse() {
    meals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLunchDetailsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              meals_ = new java.util.ArrayList<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal>();
              mutable_bitField0_ |= 0x00000001;
            }
            meals_.add(
                input.readMessage(com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        meals_ = java.util.Collections.unmodifiableList(meals_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hospital.patientsprofile.GetLunchDetailsResponse.class, com.hospital.patientsprofile.GetLunchDetailsResponse.Builder.class);
  }

  public interface MealOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetLunchDetailsResponse.Meal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string food = 1;</code>
     */
    java.lang.String getFood();
    /**
     * <code>string food = 1;</code>
     */
    com.google.protobuf.ByteString
        getFoodBytes();

    /**
     * <code>float quantity = 2;</code>
     */
    float getQuantity();

    /**
     * <code>string notes = 3;</code>
     */
    java.lang.String getNotes();
    /**
     * <code>string notes = 3;</code>
     */
    com.google.protobuf.ByteString
        getNotesBytes();
  }
  /**
   * Protobuf type {@code GetLunchDetailsResponse.Meal}
   */
  public  static final class Meal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetLunchDetailsResponse.Meal)
      MealOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Meal.newBuilder() to construct.
    private Meal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meal() {
      food_ = "";
      quantity_ = 0F;
      notes_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Meal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              food_ = s;
              break;
            }
            case 21: {

              quantity_ = input.readFloat();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              notes_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_Meal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_Meal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.class, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder.class);
    }

    public static final int FOOD_FIELD_NUMBER = 1;
    private volatile java.lang.Object food_;
    /**
     * <code>string food = 1;</code>
     */
    public java.lang.String getFood() {
      java.lang.Object ref = food_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        food_ = s;
        return s;
      }
    }
    /**
     * <code>string food = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFoodBytes() {
      java.lang.Object ref = food_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        food_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private float quantity_;
    /**
     * <code>float quantity = 2;</code>
     */
    public float getQuantity() {
      return quantity_;
    }

    public static final int NOTES_FIELD_NUMBER = 3;
    private volatile java.lang.Object notes_;
    /**
     * <code>string notes = 3;</code>
     */
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      }
    }
    /**
     * <code>string notes = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFoodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, food_);
      }
      if (quantity_ != 0F) {
        output.writeFloat(2, quantity_);
      }
      if (!getNotesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, notes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFoodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, food_);
      }
      if (quantity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, quantity_);
      }
      if (!getNotesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, notes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hospital.patientsprofile.GetLunchDetailsResponse.Meal)) {
        return super.equals(obj);
      }
      com.hospital.patientsprofile.GetLunchDetailsResponse.Meal other = (com.hospital.patientsprofile.GetLunchDetailsResponse.Meal) obj;

      boolean result = true;
      result = result && getFood()
          .equals(other.getFood());
      result = result && (
          java.lang.Float.floatToIntBits(getQuantity())
          == java.lang.Float.floatToIntBits(
              other.getQuantity()));
      result = result && getNotes()
          .equals(other.getNotes());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FOOD_FIELD_NUMBER;
      hash = (53 * hash) + getFood().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getQuantity());
      hash = (37 * hash) + NOTES_FIELD_NUMBER;
      hash = (53 * hash) + getNotes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hospital.patientsprofile.GetLunchDetailsResponse.Meal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetLunchDetailsResponse.Meal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetLunchDetailsResponse.Meal)
        com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_Meal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_Meal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.class, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder.class);
      }

      // Construct using com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        food_ = "";

        quantity_ = 0F;

        notes_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_Meal_descriptor;
      }

      @java.lang.Override
      public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal getDefaultInstanceForType() {
        return com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.getDefaultInstance();
      }

      @java.lang.Override
      public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal build() {
        com.hospital.patientsprofile.GetLunchDetailsResponse.Meal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal buildPartial() {
        com.hospital.patientsprofile.GetLunchDetailsResponse.Meal result = new com.hospital.patientsprofile.GetLunchDetailsResponse.Meal(this);
        result.food_ = food_;
        result.quantity_ = quantity_;
        result.notes_ = notes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hospital.patientsprofile.GetLunchDetailsResponse.Meal) {
          return mergeFrom((com.hospital.patientsprofile.GetLunchDetailsResponse.Meal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hospital.patientsprofile.GetLunchDetailsResponse.Meal other) {
        if (other == com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.getDefaultInstance()) return this;
        if (!other.getFood().isEmpty()) {
          food_ = other.food_;
          onChanged();
        }
        if (other.getQuantity() != 0F) {
          setQuantity(other.getQuantity());
        }
        if (!other.getNotes().isEmpty()) {
          notes_ = other.notes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hospital.patientsprofile.GetLunchDetailsResponse.Meal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hospital.patientsprofile.GetLunchDetailsResponse.Meal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object food_ = "";
      /**
       * <code>string food = 1;</code>
       */
      public java.lang.String getFood() {
        java.lang.Object ref = food_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          food_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string food = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFoodBytes() {
        java.lang.Object ref = food_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          food_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string food = 1;</code>
       */
      public Builder setFood(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        food_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string food = 1;</code>
       */
      public Builder clearFood() {
        
        food_ = getDefaultInstance().getFood();
        onChanged();
        return this;
      }
      /**
       * <code>string food = 1;</code>
       */
      public Builder setFoodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        food_ = value;
        onChanged();
        return this;
      }

      private float quantity_ ;
      /**
       * <code>float quantity = 2;</code>
       */
      public float getQuantity() {
        return quantity_;
      }
      /**
       * <code>float quantity = 2;</code>
       */
      public Builder setQuantity(float value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float quantity = 2;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object notes_ = "";
      /**
       * <code>string notes = 3;</code>
       */
      public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string notes = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string notes = 3;</code>
       */
      public Builder setNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        notes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string notes = 3;</code>
       */
      public Builder clearNotes() {
        
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      /**
       * <code>string notes = 3;</code>
       */
      public Builder setNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        notes_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetLunchDetailsResponse.Meal)
    }

    // @@protoc_insertion_point(class_scope:GetLunchDetailsResponse.Meal)
    private static final com.hospital.patientsprofile.GetLunchDetailsResponse.Meal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hospital.patientsprofile.GetLunchDetailsResponse.Meal();
    }

    public static com.hospital.patientsprofile.GetLunchDetailsResponse.Meal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Meal>
        PARSER = new com.google.protobuf.AbstractParser<Meal>() {
      @java.lang.Override
      public Meal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Meal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Meal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MEALS_FIELD_NUMBER = 1;
  private java.util.List<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal> meals_;
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  public java.util.List<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal> getMealsList() {
    return meals_;
  }
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  public java.util.List<? extends com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder> 
      getMealsOrBuilderList() {
    return meals_;
  }
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  public int getMealsCount() {
    return meals_.size();
  }
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal getMeals(int index) {
    return meals_.get(index);
  }
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  public com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder getMealsOrBuilder(
      int index) {
    return meals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < meals_.size(); i++) {
      output.writeMessage(1, meals_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < meals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, meals_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hospital.patientsprofile.GetLunchDetailsResponse)) {
      return super.equals(obj);
    }
    com.hospital.patientsprofile.GetLunchDetailsResponse other = (com.hospital.patientsprofile.GetLunchDetailsResponse) obj;

    boolean result = true;
    result = result && getMealsList()
        .equals(other.getMealsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMealsCount() > 0) {
      hash = (37 * hash) + MEALS_FIELD_NUMBER;
      hash = (53 * hash) + getMealsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.patientsprofile.GetLunchDetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hospital.patientsprofile.GetLunchDetailsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetLunchDetailsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetLunchDetailsResponse)
      com.hospital.patientsprofile.GetLunchDetailsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hospital.patientsprofile.GetLunchDetailsResponse.class, com.hospital.patientsprofile.GetLunchDetailsResponse.Builder.class);
    }

    // Construct using com.hospital.patientsprofile.GetLunchDetailsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMealsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mealsBuilder_ == null) {
        meals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        mealsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hospital.patientsprofile.ContinuousAssessment.internal_static_GetLunchDetailsResponse_descriptor;
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetLunchDetailsResponse getDefaultInstanceForType() {
      return com.hospital.patientsprofile.GetLunchDetailsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetLunchDetailsResponse build() {
      com.hospital.patientsprofile.GetLunchDetailsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hospital.patientsprofile.GetLunchDetailsResponse buildPartial() {
      com.hospital.patientsprofile.GetLunchDetailsResponse result = new com.hospital.patientsprofile.GetLunchDetailsResponse(this);
      int from_bitField0_ = bitField0_;
      if (mealsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          meals_ = java.util.Collections.unmodifiableList(meals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.meals_ = meals_;
      } else {
        result.meals_ = mealsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hospital.patientsprofile.GetLunchDetailsResponse) {
        return mergeFrom((com.hospital.patientsprofile.GetLunchDetailsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hospital.patientsprofile.GetLunchDetailsResponse other) {
      if (other == com.hospital.patientsprofile.GetLunchDetailsResponse.getDefaultInstance()) return this;
      if (mealsBuilder_ == null) {
        if (!other.meals_.isEmpty()) {
          if (meals_.isEmpty()) {
            meals_ = other.meals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMealsIsMutable();
            meals_.addAll(other.meals_);
          }
          onChanged();
        }
      } else {
        if (!other.meals_.isEmpty()) {
          if (mealsBuilder_.isEmpty()) {
            mealsBuilder_.dispose();
            mealsBuilder_ = null;
            meals_ = other.meals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            mealsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMealsFieldBuilder() : null;
          } else {
            mealsBuilder_.addAllMessages(other.meals_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hospital.patientsprofile.GetLunchDetailsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hospital.patientsprofile.GetLunchDetailsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal> meals_ =
      java.util.Collections.emptyList();
    private void ensureMealsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        meals_ = new java.util.ArrayList<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal>(meals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetLunchDetailsResponse.Meal, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder, com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder> mealsBuilder_;

    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal> getMealsList() {
      if (mealsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(meals_);
      } else {
        return mealsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public int getMealsCount() {
      if (mealsBuilder_ == null) {
        return meals_.size();
      } else {
        return mealsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal getMeals(int index) {
      if (mealsBuilder_ == null) {
        return meals_.get(index);
      } else {
        return mealsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder setMeals(
        int index, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal value) {
      if (mealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMealsIsMutable();
        meals_.set(index, value);
        onChanged();
      } else {
        mealsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder setMeals(
        int index, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder builderForValue) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.set(index, builderForValue.build());
        onChanged();
      } else {
        mealsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder addMeals(com.hospital.patientsprofile.GetLunchDetailsResponse.Meal value) {
      if (mealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMealsIsMutable();
        meals_.add(value);
        onChanged();
      } else {
        mealsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder addMeals(
        int index, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal value) {
      if (mealsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMealsIsMutable();
        meals_.add(index, value);
        onChanged();
      } else {
        mealsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder addMeals(
        com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder builderForValue) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.add(builderForValue.build());
        onChanged();
      } else {
        mealsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder addMeals(
        int index, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder builderForValue) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.add(index, builderForValue.build());
        onChanged();
      } else {
        mealsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder addAllMeals(
        java.lang.Iterable<? extends com.hospital.patientsprofile.GetLunchDetailsResponse.Meal> values) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, meals_);
        onChanged();
      } else {
        mealsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder clearMeals() {
      if (mealsBuilder_ == null) {
        meals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        mealsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public Builder removeMeals(int index) {
      if (mealsBuilder_ == null) {
        ensureMealsIsMutable();
        meals_.remove(index);
        onChanged();
      } else {
        mealsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder getMealsBuilder(
        int index) {
      return getMealsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder getMealsOrBuilder(
        int index) {
      if (mealsBuilder_ == null) {
        return meals_.get(index);  } else {
        return mealsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public java.util.List<? extends com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder> 
         getMealsOrBuilderList() {
      if (mealsBuilder_ != null) {
        return mealsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(meals_);
      }
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder addMealsBuilder() {
      return getMealsFieldBuilder().addBuilder(
          com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder addMealsBuilder(
        int index) {
      return getMealsFieldBuilder().addBuilder(
          index, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.getDefaultInstance());
    }
    /**
     * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
     */
    public java.util.List<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder> 
         getMealsBuilderList() {
      return getMealsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hospital.patientsprofile.GetLunchDetailsResponse.Meal, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder, com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder> 
        getMealsFieldBuilder() {
      if (mealsBuilder_ == null) {
        mealsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hospital.patientsprofile.GetLunchDetailsResponse.Meal, com.hospital.patientsprofile.GetLunchDetailsResponse.Meal.Builder, com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder>(
                meals_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        meals_ = null;
      }
      return mealsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetLunchDetailsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetLunchDetailsResponse)
  private static final com.hospital.patientsprofile.GetLunchDetailsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hospital.patientsprofile.GetLunchDetailsResponse();
  }

  public static com.hospital.patientsprofile.GetLunchDetailsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLunchDetailsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLunchDetailsResponse>() {
    @java.lang.Override
    public GetLunchDetailsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLunchDetailsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLunchDetailsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLunchDetailsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hospital.patientsprofile.GetLunchDetailsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

