// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital.patientsprofile;

public interface GetLunchDetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetLunchDetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  java.util.List<com.hospital.patientsprofile.GetLunchDetailsResponse.Meal> 
      getMealsList();
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  com.hospital.patientsprofile.GetLunchDetailsResponse.Meal getMeals(int index);
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  int getMealsCount();
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  java.util.List<? extends com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder> 
      getMealsOrBuilderList();
  /**
   * <code>repeated .GetLunchDetailsResponse.Meal meals = 1;</code>
   */
  com.hospital.patientsprofile.GetLunchDetailsResponse.MealOrBuilder getMealsOrBuilder(
      int index);
}
