// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientsprofile.proto

package com.hospital.patientsprofile;

public interface GetPatientInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPatientInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patient_name = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patient_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>float height = 2;</code>
   */
  float getHeight();

  /**
   * <code>float weight = 3;</code>
   */
  float getWeight();
}
