// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public final class ContinuousAssessment {
  private ContinuousAssessment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NutriInformationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NutriInformationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NutriInformationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NutriInformationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MealRankingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MealRankingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MealRankingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MealRankingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MicroNutrientStatsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MicroNutrientStatsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MicroNutrientStatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MicroNutrientStatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MicroNutrientStatsResponse_NutrientInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MicroNutrientStatsResponse_NutrientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034nutritionalinformation.proto\".\n\027NutriI" +
      "nformationRequest\022\023\n\013meal_number\030\001 \001(\005\"4" +
      "\n\030NutriInformationResponse\022\030\n\020meal_ingre" +
      "dients\030\001 \001(\t\"\'\n\022MealRankingRequest\022\021\n\tme" +
      "al_type\030\001 \001(\005\")\n\023MealRankingResponse\022\022\n\n" +
      "avg_rating\030\001 \001(\002\"1\n\031MicroNutrientStatsRe" +
      "quest\022\024\n\014meal_numbers\030\001 \003(\005\"\235\001\n\032MicroNut" +
      "rientStatsResponse\022@\n\016nutrient_infos\030\001 \003" +
      "(\0132(.MicroNutrientStatsResponse.Nutrient" +
      "Info\032=\n\014NutrientInfo\022\025\n\rnutrient_name\030\001 " +
      "\001(\t\022\026\n\016nutrient_value\030\002 \001(\0022\373\001\n\035Nutritio" +
      "nalInformationService\022I\n\020nutriInformatio" +
      "n\022\030.NutriInformationRequest\032\031.NutriInfor" +
      "mationResponse\"\000\022:\n\013mealRanking\022\023.MealRa" +
      "nkingRequest\032\024.MealRankingResponse\"\000\022S\n\022" +
      "microNutrientStats\022\032.MicroNutrientStatsR" +
      "equest\032\033.MicroNutrientStatsResponse\"\000(\0010" +
      "\001B=\n#com.hospital.nutritionalinformation" +
      "B\024ContinuousAssessmentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NutriInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NutriInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NutriInformationRequest_descriptor,
        new java.lang.String[] { "MealNumber", });
    internal_static_NutriInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NutriInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NutriInformationResponse_descriptor,
        new java.lang.String[] { "MealIngredients", });
    internal_static_MealRankingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MealRankingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MealRankingRequest_descriptor,
        new java.lang.String[] { "MealType", });
    internal_static_MealRankingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MealRankingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MealRankingResponse_descriptor,
        new java.lang.String[] { "AvgRating", });
    internal_static_MicroNutrientStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MicroNutrientStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MicroNutrientStatsRequest_descriptor,
        new java.lang.String[] { "MealNumbers", });
    internal_static_MicroNutrientStatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_MicroNutrientStatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MicroNutrientStatsResponse_descriptor,
        new java.lang.String[] { "NutrientInfos", });
    internal_static_MicroNutrientStatsResponse_NutrientInfo_descriptor =
      internal_static_MicroNutrientStatsResponse_descriptor.getNestedTypes().get(0);
    internal_static_MicroNutrientStatsResponse_NutrientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MicroNutrientStatsResponse_NutrientInfo_descriptor,
        new java.lang.String[] { "NutrientName", "NutrientValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
