// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public interface MealRankingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MealRankingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float avg_rating = 1;</code>
   */
  float getAvgRating();
}
