// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

/**
 * Protobuf type {@code MealRankingResponse}
 */
public  final class MealRankingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MealRankingResponse)
    MealRankingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MealRankingResponse.newBuilder() to construct.
  private MealRankingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MealRankingResponse() {
    avgRating_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MealRankingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            avgRating_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MealRankingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MealRankingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hospital.nutritionalinformation.MealRankingResponse.class, com.hospital.nutritionalinformation.MealRankingResponse.Builder.class);
  }

  public static final int AVG_RATING_FIELD_NUMBER = 1;
  private float avgRating_;
  /**
   * <code>float avg_rating = 1;</code>
   */
  public float getAvgRating() {
    return avgRating_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (avgRating_ != 0F) {
      output.writeFloat(1, avgRating_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (avgRating_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, avgRating_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hospital.nutritionalinformation.MealRankingResponse)) {
      return super.equals(obj);
    }
    com.hospital.nutritionalinformation.MealRankingResponse other = (com.hospital.nutritionalinformation.MealRankingResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getAvgRating())
        == java.lang.Float.floatToIntBits(
            other.getAvgRating()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVG_RATING_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAvgRating());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.nutritionalinformation.MealRankingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hospital.nutritionalinformation.MealRankingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MealRankingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MealRankingResponse)
      com.hospital.nutritionalinformation.MealRankingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MealRankingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MealRankingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hospital.nutritionalinformation.MealRankingResponse.class, com.hospital.nutritionalinformation.MealRankingResponse.Builder.class);
    }

    // Construct using com.hospital.nutritionalinformation.MealRankingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      avgRating_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MealRankingResponse_descriptor;
    }

    @java.lang.Override
    public com.hospital.nutritionalinformation.MealRankingResponse getDefaultInstanceForType() {
      return com.hospital.nutritionalinformation.MealRankingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hospital.nutritionalinformation.MealRankingResponse build() {
      com.hospital.nutritionalinformation.MealRankingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hospital.nutritionalinformation.MealRankingResponse buildPartial() {
      com.hospital.nutritionalinformation.MealRankingResponse result = new com.hospital.nutritionalinformation.MealRankingResponse(this);
      result.avgRating_ = avgRating_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hospital.nutritionalinformation.MealRankingResponse) {
        return mergeFrom((com.hospital.nutritionalinformation.MealRankingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hospital.nutritionalinformation.MealRankingResponse other) {
      if (other == com.hospital.nutritionalinformation.MealRankingResponse.getDefaultInstance()) return this;
      if (other.getAvgRating() != 0F) {
        setAvgRating(other.getAvgRating());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hospital.nutritionalinformation.MealRankingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hospital.nutritionalinformation.MealRankingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float avgRating_ ;
    /**
     * <code>float avg_rating = 1;</code>
     */
    public float getAvgRating() {
      return avgRating_;
    }
    /**
     * <code>float avg_rating = 1;</code>
     */
    public Builder setAvgRating(float value) {
      
      avgRating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float avg_rating = 1;</code>
     */
    public Builder clearAvgRating() {
      
      avgRating_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MealRankingResponse)
  }

  // @@protoc_insertion_point(class_scope:MealRankingResponse)
  private static final com.hospital.nutritionalinformation.MealRankingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hospital.nutritionalinformation.MealRankingResponse();
  }

  public static com.hospital.nutritionalinformation.MealRankingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MealRankingResponse>
      PARSER = new com.google.protobuf.AbstractParser<MealRankingResponse>() {
    @java.lang.Override
    public MealRankingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MealRankingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MealRankingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MealRankingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hospital.nutritionalinformation.MealRankingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

