// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public interface MealRankingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MealRankingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 meal_type = 1;</code>
   */
  int getMealType();
}
