// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public interface MicroNutrientStatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MicroNutrientStatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MicroNutrientStatsResponse.NutrientInfo nutrient_infos = 1;</code>
   */
  java.util.List<com.hospital.nutritionalinformation.MicroNutrientStatsResponse.NutrientInfo> 
      getNutrientInfosList();
  /**
   * <code>repeated .MicroNutrientStatsResponse.NutrientInfo nutrient_infos = 1;</code>
   */
  com.hospital.nutritionalinformation.MicroNutrientStatsResponse.NutrientInfo getNutrientInfos(int index);
  /**
   * <code>repeated .MicroNutrientStatsResponse.NutrientInfo nutrient_infos = 1;</code>
   */
  int getNutrientInfosCount();
  /**
   * <code>repeated .MicroNutrientStatsResponse.NutrientInfo nutrient_infos = 1;</code>
   */
  java.util.List<? extends com.hospital.nutritionalinformation.MicroNutrientStatsResponse.NutrientInfoOrBuilder> 
      getNutrientInfosOrBuilderList();
  /**
   * <code>repeated .MicroNutrientStatsResponse.NutrientInfo nutrient_infos = 1;</code>
   */
  com.hospital.nutritionalinformation.MicroNutrientStatsResponse.NutrientInfoOrBuilder getNutrientInfosOrBuilder(
      int index);
}
