// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public interface MicroNutrientStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MicroNutrientStatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 meal_numbers = 1;</code>
   */
  java.util.List<java.lang.Integer> getMealNumbersList();
  /**
   * <code>repeated int32 meal_numbers = 1;</code>
   */
  int getMealNumbersCount();
  /**
   * <code>repeated int32 meal_numbers = 1;</code>
   */
  int getMealNumbers(int index);
}
