// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

/**
 * Protobuf type {@code MicroNutrientStatsRequest}
 */
public  final class MicroNutrientStatsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MicroNutrientStatsRequest)
    MicroNutrientStatsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MicroNutrientStatsRequest.newBuilder() to construct.
  private MicroNutrientStatsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MicroNutrientStatsRequest() {
    mealNumbers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MicroNutrientStatsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              mealNumbers_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            mealNumbers_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              mealNumbers_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              mealNumbers_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        mealNumbers_ = java.util.Collections.unmodifiableList(mealNumbers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MicroNutrientStatsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MicroNutrientStatsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hospital.nutritionalinformation.MicroNutrientStatsRequest.class, com.hospital.nutritionalinformation.MicroNutrientStatsRequest.Builder.class);
  }

  public static final int MEAL_NUMBERS_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> mealNumbers_;
  /**
   * <code>repeated int32 meal_numbers = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getMealNumbersList() {
    return mealNumbers_;
  }
  /**
   * <code>repeated int32 meal_numbers = 1;</code>
   */
  public int getMealNumbersCount() {
    return mealNumbers_.size();
  }
  /**
   * <code>repeated int32 meal_numbers = 1;</code>
   */
  public int getMealNumbers(int index) {
    return mealNumbers_.get(index);
  }
  private int mealNumbersMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getMealNumbersList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(mealNumbersMemoizedSerializedSize);
    }
    for (int i = 0; i < mealNumbers_.size(); i++) {
      output.writeInt32NoTag(mealNumbers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < mealNumbers_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(mealNumbers_.get(i));
      }
      size += dataSize;
      if (!getMealNumbersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      mealNumbersMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hospital.nutritionalinformation.MicroNutrientStatsRequest)) {
      return super.equals(obj);
    }
    com.hospital.nutritionalinformation.MicroNutrientStatsRequest other = (com.hospital.nutritionalinformation.MicroNutrientStatsRequest) obj;

    boolean result = true;
    result = result && getMealNumbersList()
        .equals(other.getMealNumbersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMealNumbersCount() > 0) {
      hash = (37 * hash) + MEAL_NUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMealNumbersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hospital.nutritionalinformation.MicroNutrientStatsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MicroNutrientStatsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MicroNutrientStatsRequest)
      com.hospital.nutritionalinformation.MicroNutrientStatsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MicroNutrientStatsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MicroNutrientStatsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hospital.nutritionalinformation.MicroNutrientStatsRequest.class, com.hospital.nutritionalinformation.MicroNutrientStatsRequest.Builder.class);
    }

    // Construct using com.hospital.nutritionalinformation.MicroNutrientStatsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mealNumbers_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hospital.nutritionalinformation.ContinuousAssessment.internal_static_MicroNutrientStatsRequest_descriptor;
    }

    @java.lang.Override
    public com.hospital.nutritionalinformation.MicroNutrientStatsRequest getDefaultInstanceForType() {
      return com.hospital.nutritionalinformation.MicroNutrientStatsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.hospital.nutritionalinformation.MicroNutrientStatsRequest build() {
      com.hospital.nutritionalinformation.MicroNutrientStatsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hospital.nutritionalinformation.MicroNutrientStatsRequest buildPartial() {
      com.hospital.nutritionalinformation.MicroNutrientStatsRequest result = new com.hospital.nutritionalinformation.MicroNutrientStatsRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        mealNumbers_ = java.util.Collections.unmodifiableList(mealNumbers_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.mealNumbers_ = mealNumbers_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hospital.nutritionalinformation.MicroNutrientStatsRequest) {
        return mergeFrom((com.hospital.nutritionalinformation.MicroNutrientStatsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hospital.nutritionalinformation.MicroNutrientStatsRequest other) {
      if (other == com.hospital.nutritionalinformation.MicroNutrientStatsRequest.getDefaultInstance()) return this;
      if (!other.mealNumbers_.isEmpty()) {
        if (mealNumbers_.isEmpty()) {
          mealNumbers_ = other.mealNumbers_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMealNumbersIsMutable();
          mealNumbers_.addAll(other.mealNumbers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hospital.nutritionalinformation.MicroNutrientStatsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hospital.nutritionalinformation.MicroNutrientStatsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> mealNumbers_ = java.util.Collections.emptyList();
    private void ensureMealNumbersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        mealNumbers_ = new java.util.ArrayList<java.lang.Integer>(mealNumbers_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getMealNumbersList() {
      return java.util.Collections.unmodifiableList(mealNumbers_);
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public int getMealNumbersCount() {
      return mealNumbers_.size();
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public int getMealNumbers(int index) {
      return mealNumbers_.get(index);
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public Builder setMealNumbers(
        int index, int value) {
      ensureMealNumbersIsMutable();
      mealNumbers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public Builder addMealNumbers(int value) {
      ensureMealNumbersIsMutable();
      mealNumbers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public Builder addAllMealNumbers(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureMealNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mealNumbers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 meal_numbers = 1;</code>
     */
    public Builder clearMealNumbers() {
      mealNumbers_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MicroNutrientStatsRequest)
  }

  // @@protoc_insertion_point(class_scope:MicroNutrientStatsRequest)
  private static final com.hospital.nutritionalinformation.MicroNutrientStatsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hospital.nutritionalinformation.MicroNutrientStatsRequest();
  }

  public static com.hospital.nutritionalinformation.MicroNutrientStatsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MicroNutrientStatsRequest>
      PARSER = new com.google.protobuf.AbstractParser<MicroNutrientStatsRequest>() {
    @java.lang.Override
    public MicroNutrientStatsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MicroNutrientStatsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MicroNutrientStatsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MicroNutrientStatsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hospital.nutritionalinformation.MicroNutrientStatsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

