// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public interface NutriInformationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NutriInformationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 meal_number = 1;</code>
   */
  int getMealNumber();
}
