// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nutritionalinformation.proto

package com.hospital.nutritionalinformation;

public interface NutriInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NutriInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meal_ingredients = 1;</code>
   */
  java.lang.String getMealIngredients();
  /**
   * <code>string meal_ingredients = 1;</code>
   */
  com.google.protobuf.ByteString
      getMealIngredientsBytes();
}
