// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portioncalculator.proto

package com.hospital.portioncalculator;

public interface CurrentPortionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrentPortionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string food = 1;</code>
   */
  java.lang.String getFood();
  /**
   * <code>string food = 1;</code>
   */
  com.google.protobuf.ByteString
      getFoodBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
