// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portioncalculator.proto

package com.hospital.portioncalculator;

public interface SuitableMealResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SuitableMealResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SuitableMealResponse.DietLevel diet_level = 1;</code>
   */
  int getDietLevelValue();
  /**
   * <code>.SuitableMealResponse.DietLevel diet_level = 1;</code>
   */
  com.hospital.portioncalculator.SuitableMealResponse.DietLevel getDietLevel();
}
